### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BigDeepBlue** [alena-kono/ugc-service-2#7]
Все отлично 👍 Код очень хороший.
1. Конфигурацию ELK рекомендую слегка изменить. [Вот тут](https://github.com/alena-kono/ugc-service-2/blob/91725f76fab4702a74daacc53350fa37a6a29b53/docker/elk/logstash.conf#L13) вы все кладете в один индекс, но в приложении у вас уже множество сервисов (выдачи контента, авторизации, ugc, админка и т.д.). Из одного индекса вылавливать все это будет крайне сложно. Попробуйте разделить, например так:
      ```
      ...
         if ( [tag] == "auth_app" ) {
            elasticsearch {
              hosts => [ "${ES_HOST}" ]
              index => "auth_app-%{+YYYY.MM.dd}"
            }
        }
        else if ( [tag] == "fast_api_app" ) {
            elasticsearch {
              hosts => [ "${ES_HOST}" ]
              index => "fast_api_app-%{+YYYY.MM.dd}"
            }
        }
      ...
      ```
2. [просто к сведению] В этом спринте нужно было выбрать и провести исследование хранилища для частой записи и чтения по одной записи. Ведь именно так и будет происходить с лайками, рецензиями и закладками. В то же время предполагаем, что таких записей будет ооооочень много. Кликхаус для сравнения сразу не подходит, там сами производителя утверждают, что вставлять нужно не менее чем 1000 записей за один раз, иначе он будет падать. Читать из Кликхауса по одной записи - вообще приключение, он для другого предназначек, он любит и умеет агрегационные запросы.
Тогда встает вопрос: что же сравнивать? Можно mongo и postgres, они отлично подходят для поставленной задачи.
3. API сервиса UGC не очень хорошо покрыто тестами. Давайте хотя бы несколько эндпоинтов потестируем.
4. [можно лучше] В API реализованы лайки и рецензии, в ТЗ было и про закладки.

**Comment by alena-kono** [comment]
@BigDeepBlue Спасибо! Все поправили, кроме п. 4. Решили пока, что в целом, "bookmarks" можем заменить "film_progress" метками.

**Comment by BigDeepBlue** [comment]
LGTM
